set(_AMENT_PACKAGE_NAME "hardware_interface_linrob_package")
set(hardware_interface_linrob_package_VERSION "0.0.0")
set(hardware_interface_linrob_package_MAINTAINER "Your Name <selim.ouirari@linrob.io>")
set(hardware_interface_linrob_package_BUILD_DEPENDS "rosidl_default_generators" "rclcpp" "rclcpp_action" "rclpy" "std_msgs" "action_msgs" "builtin_interfaces" "rosidl_default_runtime" "launch" "launch_ros")
set(hardware_interface_linrob_package_BUILDTOOL_DEPENDS "ament_cmake")
set(hardware_interface_linrob_package_BUILD_EXPORT_DEPENDS "rclcpp" "rclcpp_action" "rclpy" "std_msgs" "action_msgs" "builtin_interfaces" "rosidl_default_runtime" "launch" "launch_ros")
set(hardware_interface_linrob_package_BUILDTOOL_EXPORT_DEPENDS )
set(hardware_interface_linrob_package_EXEC_DEPENDS "rclcpp" "rclcpp_action" "rclpy" "std_msgs" "action_msgs" "builtin_interfaces" "rosidl_default_runtime" "launch" "launch_ros")
set(hardware_interface_linrob_package_TEST_DEPENDS "ament_lint_auto" "ament_lint_common" "python3-pytest")
set(hardware_interface_linrob_package_GROUP_DEPENDS )
set(hardware_interface_linrob_package_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(hardware_interface_linrob_package_DEPRECATED "")
set(hardware_interface_linrob_package_EXPORT_TAGS)
list(APPEND hardware_interface_linrob_package_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
